function [ inducedVelocity ] = induced_velocity_propeller( propData, ...
    airspeed, spinnerRadius )

% Swirl generated by the propeller

k = size(propData,1);

radius = propData(:,1);
radius2 = propData(:,2);
inducedSpeed = propData(:,3);
rotationSpeed = propData(:,4);
    
vSwirl = zeros(k,1);
inducedVelocity = zeros(k,3);

for i=1:k
    if abs(radius(i)) < spinnerRadius
        if radius2(i) > 0
            vSwirl(i) = radius(i)/spinnerRadius ...
                * 2 * inducedSpeed(i) * norm(airspeed) / ...
                ( rotationSpeed(i) * spinnerRadius ) ;
        else
            vSwirl(i) = 0;
        end
    else
        vSwirl(i) = 2 * inducedSpeed(i) * norm(airspeed) / ...
            ( rotationSpeed(i) * radius(i) );
    end
end

airflow = inducedSpeed .* radius2;

inducedVelocity(:,1) = airflow;
inducedVelocity(:,3) = vSwirl;

end

